export const FETCHACTIVITIES = 'FETCHACTIVITIES';
export const FETCHBABIES = 'FETCHBABIES';
export const FETCHASSISTANTS = 'FETCHASSISTANTS';
export const FETCHACTIVITYLOGS = 'FETCHACTIVITYLOGS';
export const FETCHACTIVITYLOG = 'FETCHACTIVITYLOG';
export const CREATEACTIVITYLOG = 'CREATEACTIVITYLOG';
export const EDITACTIVITYLOG = 'EDITACTIVITYLOG';